services:
  mysql:
    image: mariadb:11.7.2
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: thoth
      MYSQL_USER: thoth
      MYSQL_PASSWORD: 1234
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
