// THOTH-067: adds a cosmetic title slug to page detail URLs, turning
// `/{workspaceSlug}/pages/{id}` into `/{workspaceSlug}/pages/{titleSlug}-{id}`. The slug is
// purely for display/readability — every lookup still resolves by `id` alone, so bookmarked or
// hand-typed bare-`id` URLs (and any URL for a page whose `id` doesn't look machine-generated,
// e.g. seeded fixture ids containing dashes) keep working unchanged.

// Real `Container` ids are generated by SuperSave via `short-uuid`'s default (flickrBase58)
// alphabet, which always produces a fixed-length 22-character alphanumeric string with no
// dashes. Only ids matching this shape are eligible for a slug prefix — this keeps the
// `{slug}-{id}` combination round-trippable: everything up to the last dash is the slug, and the
// last dash-free segment is unambiguously the real id (it can't itself contain a dash, and the
// slug alone never matches this pattern since it's always lowercased/hyphenated).
const GENERATED_ID_PATTERN = /^[0-9A-Za-z]{22}$/;

const TITLE_SLUG_MAX_LENGTH = 30;

/**
 * Converts a page name into a URL-safe slug: lowercase, alphanumeric segments joined by single
 * hyphens, truncated to `TITLE_SLUG_MAX_LENGTH` characters. Returns an empty string if the name
 * is missing or contains no usable characters (e.g. all-emoji), signalling "no slug available"
 * to `buildPageUrlId` rather than falling back to a placeholder word.
 */
export function createTitleSlug(name: string | null | undefined): string {
  if (!name) {
    return '';
  }

  return name
    .normalize('NFKD')
    .replaceAll(/[\u0300-\u036F]/g, '')
    .toLowerCase()
    .replaceAll(/[^a-z0-9]+/g, '-')
    .replaceAll(/^-+|-+$/g, '')
    .slice(0, TITLE_SLUG_MAX_LENGTH)
    .replaceAll(/-+$/g, '');
}

/**
 * Builds the `[id]` route segment for a page detail URL: `{titleSlug}-{id}` when both a usable
 * slug and a generated-shape `id` are available, otherwise just the bare `id`.
 */
export function buildPageUrlId(id: string, name?: string | null): string {
  const slug = createTitleSlug(name);

  if (!slug || !GENERATED_ID_PATTERN.test(id)) {
    return id;
  }

  return `${slug}-${id}`;
}

/**
 * Extracts the real page `id` from a page detail route's `[id]` segment, which may be a bare
 * `id` (legacy links, or any id that never got a slug prefix) or a `{titleSlug}-{id}` combo.
 * Only strips a prefix when the trailing dash-free segment matches the generated-id shape, so a
 * dash-containing legacy/custom id is always returned unchanged.
 */
export function extractPageId(routeParameter: string): string {
  if (GENERATED_ID_PATTERN.test(routeParameter)) {
    return routeParameter;
  }

  const lastDashIndex = routeParameter.lastIndexOf('-');
  if (lastDashIndex === -1) {
    return routeParameter;
  }

  const candidate = routeParameter.slice(lastDashIndex + 1);
  return GENERATED_ID_PATTERN.test(candidate) ? candidate : routeParameter;
}
