import * as api from '@/types/api';
import type { OperationRegistry } from './types';

/**
 * Build-time registry for the OpenAPI generator.
 *
 * Intentionally excluded:
 * - `src/app/api/auth/[...auth]/route.ts`: Better Auth catch-all handler, not wrapped by `apiRoute`.
 * - `src/app/api/health/route.ts`: operational health probe, not part of the product API surface.
 * - `POST /files` and `GET /files/{id}/content` (`src/app/api/v1/files/route.ts`,
 *   `src/app/api/v1/files/[id]/content/route.ts`): manual handlers (multipart request body /
 *   binary streaming response), not wrapped by `apiRoute`, so not part of the generated schema.
 * - `GET /pages/{id}/markdown` (`src/app/api/v1/pages/[id]/markdown/route.ts`, THOTH-048): manual
 *   handler returning the raw Markdown body as `text/markdown` (not JSON), so not wrapped by
 *   `apiRoute` and not part of the generated schema. It's the internal rewrite target for the
 *   `.md`-suffixed page detail URL, not a documented API surface of its own.
 * - `GET /notifications/{id}/open` (`src/app/notifications/[id]/open/route.ts`, THOTH-066): manual
 *   handler (NOT under `/api`, NOT wrapped by `apiRoute`) that marks an inbox item read and
 *   303-redirects to the target page. It's an in-app navigation route, not a documented API
 *   surface of its own.
 * - `/admin/*` (`src/app/api/v1/admin/**`, THOTH-045): platform-administrator-only operational
 *   endpoints (settings, per-user and per-workspace storage quotas). Deliberately excluded from
 *   the public API document — they are an internal administration surface, not part of the
 *   product API. (`GET /platform/capabilities` IS documented — it's a capability probe usable by
 *   any authenticated human.)
 *
 * `/config` is registered as `/config` even though `GET_AUTH_CONFIG_ENDPOINT` is `/v1/config`,
 * because the generated document is served with `/api/v1` as its server base URL.
 */
export const operations = [
  {
    path: '/pages/tree',
    method: 'get',
    operationId: 'getPagesTree',
    summary: 'List the page tree',
    tags: ['Pages'],
    auth: 'sessionOrApiKey',
    query: api.getPagesTreeQueryVariablesSchema,
    response: api.getPagesTreeResponseSchema,
    errorStatuses: [404],
  },
  {
    path: '/pages',
    method: 'get',
    operationId: 'getPages',
    summary: 'List pages',
    tags: ['Pages'],
    auth: 'sessionOrApiKey',
    query: api.getPagesQuerySchema,
    response: api.getPagesResponseSchema,
    // Only populated for the `viewId`-driven, cursor-paginated path (THOTH-037); every other
    // query shape (favorited/recent/parentId/dataSourceId) omits it.
    responseMeta: { pagination: api.getPagesPaginationSchema },
  },
  {
    path: '/pages',
    method: 'post',
    operationId: 'createPage',
    summary: 'Create a page',
    tags: ['Pages'],
    auth: 'sessionOrApiKey',
    body: api.createPageBodySchema,
    response: api.createPageResponseSchema,
    successStatus: 201,
    errorStatuses: [404],
  },
  {
    path: '/pages/welcome',
    method: 'post',
    operationId: 'createWelcomePage',
    summary: 'Create the welcome page',
    tags: ['Pages'],
    auth: 'sessionOrApiKey',
    body: api.createWelcomePageBodySchema,
    response: api.createWelcomePageResponseSchema,
    successStatus: 201,
    errorStatuses: [404],
  },
  {
    path: '/pages/{id}/append',
    method: 'post',
    operationId: 'appendPageContent',
    summary: 'Append page content',
    tags: ['Pages'],
    auth: 'sessionOrApiKey',
    params: api.mutatePageContentParametersSchema,
    body: api.mutatePageContentBodySchema,
    response: api.mutatePageContentResponseSchema,
    successStatus: 200,
  },
  {
    path: '/pages/{id}/values',
    method: 'patch',
    operationId: 'updatePageValues',
    summary: 'Update page values',
    tags: ['Pages'],
    auth: 'sessionOrApiKey',
    params: api.updatePageValuesParametersSchema,
    body: api.updatePageValuesBodySchema,
    successStatus: 204,
  },
  {
    path: '/pages/{id}',
    method: 'get',
    operationId: 'getPageDetails',
    summary: 'Get page details',
    tags: ['Pages'],
    auth: 'sessionOrApiKey',
    query: api.getPageDetailsQuerySchema,
    params: api.getPageDetailsParametersSchema,
    response: api.getPageDetailsResponseSchema,
  },
  {
    path: '/pages/{id}',
    method: 'patch',
    operationId: 'updatePage',
    summary: 'Update a page',
    tags: ['Pages'],
    auth: 'sessionOrApiKey',
    params: api.updatePageParametersSchema,
    body: api.updatePageBodySchema,
    response: api.updatePageResponseSchema,
    successStatus: 200,
  },
  {
    path: '/pages/{id}',
    method: 'delete',
    operationId: 'deletePage',
    summary: 'Soft-delete a page',
    tags: ['Pages'],
    auth: 'sessionOrApiKey',
    params: api.deletePageParametersSchema,
    successStatus: 204,
  },
  {
    path: '/pages/{id}/restore',
    method: 'post',
    operationId: 'restorePage',
    summary: 'Restore a soft-deleted page',
    tags: ['Pages'],
    auth: 'sessionOrApiKey',
    params: api.restorePageParametersSchema,
    response: api.restorePageResponseSchema,
    successStatus: 200,
    errorStatuses: [410],
  },
  {
    path: '/pages/{id}/permanent',
    method: 'delete',
    operationId: 'permanentDeletePage',
    summary: 'Permanently delete a soft-deleted page',
    tags: ['Pages'],
    auth: 'session',
    params: api.permanentDeletePageParametersSchema,
    successStatus: 204,
  },
  {
    path: '/pages/{id}/access',
    method: 'post',
    operationId: 'registerPageAccess',
    summary: 'Register page access',
    tags: ['Pages'],
    auth: 'sessionOrApiKey',
    params: api.registerPageAccessParametersSchema,
    response: api.registerPageAccessResponseSchema,
    successStatus: 200,
  },
  {
    path: '/pages/{id}/prepend',
    method: 'post',
    operationId: 'prependPageContent',
    summary: 'Prepend page content',
    tags: ['Pages'],
    auth: 'sessionOrApiKey',
    params: api.mutatePageContentParametersSchema,
    body: api.mutatePageContentBodySchema,
    response: api.mutatePageContentResponseSchema,
    successStatus: 200,
  },
  {
    path: '/pages/{id}/content',
    method: 'get',
    operationId: 'getPageContent',
    summary: 'Get page content',
    tags: ['Pages'],
    auth: 'sessionOrApiKey',
    params: api.getPageContentParametersSchema,
    response: api.getPageContentResponseSchema,
  },
  {
    path: '/pages/{id}/content',
    method: 'post',
    operationId: 'setPageContent',
    summary: 'Replace page content',
    tags: ['Pages'],
    auth: 'sessionOrApiKey',
    params: api.setPageContentParametersSchema,
    body: api.setPageContentBodySchema,
    successStatus: 204,
  },
  {
    path: '/pages/{id}/favorite',
    method: 'put',
    operationId: 'setPageFavorite',
    summary: 'Set page favorite state',
    tags: ['Pages'],
    auth: 'sessionOrApiKey',
    params: api.putPageFavoriteParametersSchema,
    body: api.putPageFavoriteBodySchema,
    response: api.putPageFavoriteResponseSchema,
    successStatus: 200,
  },
  {
    path: '/pages/{id}/reorder',
    method: 'post',
    operationId: 'reorderPage',
    summary: 'Reorder a page within its sibling group',
    tags: ['Pages'],
    auth: 'sessionOrApiKey',
    params: api.reorderPageParametersSchema,
    body: api.reorderPageBodySchema,
    response: api.reorderPageResponseSchema,
    successStatus: 200,
    errorStatuses: [400, 404],
  },
  {
    path: '/pages/{id}/breadcrumbs',
    method: 'get',
    operationId: 'getPageBreadcrumbs',
    summary: 'Get page breadcrumbs',
    tags: ['Pages'],
    auth: 'sessionOrApiKey',
    params: api.getPageBreadcrumbsParametersSchema,
    response: api.getPageBreadcrumbsResponseSchema,
  },
  {
    path: '/pages/{id}/history',
    method: 'get',
    operationId: 'getPageHistory',
    summary: 'List page revision history',
    tags: ['Pages'],
    auth: 'sessionOrApiKey',
    params: api.getPageHistoryParametersSchema,
    query: api.getPageHistoryQuerySchema,
    response: api.getPageHistoryResponseSchema,
    errorStatuses: [403, 404],
  },
  {
    path: '/pages/{id}/history/{revisionId}',
    method: 'get',
    operationId: 'getPageRevision',
    summary: 'Reconstruct a page revision and diff it against the current state',
    tags: ['Pages'],
    auth: 'sessionOrApiKey',
    params: api.getPageRevisionParametersSchema,
    response: api.getPageRevisionResponseSchema,
    errorStatuses: [403, 404],
  },
  {
    path: '/pages/{id}/history/{revisionId}/restore',
    method: 'post',
    operationId: 'restorePageRevision',
    summary: 'Restore the current page to a historical revision',
    tags: ['Pages'],
    auth: 'sessionOrApiKey',
    params: api.restorePageRevisionParametersSchema,
    response: api.restorePageRevisionResponseSchema,
    successStatus: 200,
    errorStatuses: [404],
  },
  {
    path: '/pages/{id}/history/{revisionId}/fork',
    method: 'post',
    operationId: 'forkPageRevision',
    summary: 'Create a new page seeded from a historical revision',
    tags: ['Pages'],
    auth: 'sessionOrApiKey',
    params: api.forkPageRevisionParametersSchema,
    body: api.forkPageRevisionBodySchema,
    response: api.forkPageRevisionResponseSchema,
    successStatus: 201,
    errorStatuses: [404],
  },
  {
    path: '/pages/{id}/apps',
    method: 'get',
    operationId: 'getPageApps',
    summary: 'List page app connections',
    tags: ['Pages', 'Apps'],
    auth: 'session',
    params: api.pageAppsParametersSchema,
    response: api.getPageAppsResponseSchema,
  },
  {
    path: '/pages/{id}/apps',
    method: 'post',
    operationId: 'connectPageApp',
    summary: 'Connect an app to a page',
    tags: ['Pages', 'Apps'],
    auth: 'session',
    params: api.pageAppsParametersSchema,
    body: api.connectPageAppBodySchema,
    response: api.connectPageAppResponseSchema,
    successStatus: 200,
  },
  {
    path: '/pages/{id}/apps/{appId}',
    method: 'delete',
    operationId: 'disconnectPageApp',
    summary: 'Disconnect an app from a page',
    tags: ['Pages', 'Apps'],
    auth: 'session',
    params: api.disconnectPageAppParametersSchema,
    successStatus: 204,
  },
  {
    path: '/pages/deleted',
    method: 'get',
    operationId: 'getDeletedPages',
    summary: 'List soft-deleted pages, data sources, and views',
    tags: ['Pages'],
    auth: 'session',
    query: api.getDeletedPagesQuerySchema,
    response: api.getDeletedPagesResponseSchema,
  },
  {
    path: '/pages/deleted/restore',
    method: 'post',
    operationId: 'batchRestoreDeletedPages',
    summary: 'Restore deleted items from trash',
    tags: ['Pages'],
    auth: 'session',
    body: api.batchTrashBodySchema,
    response: api.batchRestorePagesResponseSchema,
    successStatus: 200,
  },
  {
    path: '/pages/deleted/delete',
    method: 'post',
    operationId: 'batchDeleteDeletedPages',
    summary: 'Permanently delete items from trash',
    tags: ['Pages'],
    auth: 'session',
    body: api.batchTrashBodySchema,
    response: api.batchDeletePagesResponseSchema,
    successStatus: 200,
  },
  {
    path: '/views',
    method: 'get',
    operationId: 'getDataViews',
    summary: 'List data views',
    tags: ['Views'],
    auth: 'sessionOrApiKey',
    query: api.getDataViewsQuerySchema,
    response: api.getDataViewsResponseSchema,
  },
  {
    path: '/views',
    method: 'post',
    operationId: 'createDataView',
    summary: 'Create a data view',
    tags: ['Views'],
    auth: 'sessionOrApiKey',
    body: api.createDataViewBodySchema,
    response: api.createDataViewResponseSchema,
    successStatus: 201,
    errorStatuses: [404],
  },
  {
    path: '/views/{id}',
    method: 'get',
    operationId: 'getDataView',
    summary: 'Get a data view',
    tags: ['Views'],
    auth: 'sessionOrApiKey',
    params: api.getDataViewParametersSchema,
    response: api.getDataViewResponseSchema,
  },
  {
    path: '/views/{id}',
    method: 'patch',
    operationId: 'updateDataView',
    summary: 'Update a data view',
    tags: ['Views'],
    auth: 'sessionOrApiKey',
    params: api.updateDataViewParametersSchema,
    body: api.updateDataViewBodySchema,
    response: api.updateDataViewResponseSchema,
    successStatus: 200,
    errorStatuses: [400, 409],
  },
  {
    path: '/views/{id}',
    method: 'delete',
    operationId: 'deleteDataView',
    summary: 'Soft-delete a data view',
    tags: ['Views'],
    auth: 'sessionOrApiKey',
    params: api.deleteViewParametersSchema,
    successStatus: 204,
  },
  {
    path: '/views/{id}/restore',
    method: 'post',
    operationId: 'restoreDataView',
    summary: 'Restore a soft-deleted data view',
    tags: ['Views'],
    auth: 'sessionOrApiKey',
    params: api.restoreViewParametersSchema,
    response: api.restoreViewResponseSchema,
    successStatus: 200,
    errorStatuses: [410],
  },
  {
    path: '/workspaces/deleted',
    method: 'get',
    operationId: 'getDeletedWorkspaces',
    summary: 'List soft-deleted workspaces',
    tags: ['Workspaces'],
    auth: 'sessionOrApiKey',
    response: api.getDeletedWorkspacesResponseSchema,
  },
  {
    path: '/workspaces',
    method: 'get',
    operationId: 'getWorkspaces',
    summary: 'List workspaces',
    tags: ['Workspaces'],
    auth: 'sessionOrApiKey',
    response: api.getWorkspacesResponseSchema,
  },
  {
    path: '/workspaces',
    method: 'post',
    operationId: 'createWorkspace',
    summary: 'Create a workspace',
    tags: ['Workspaces'],
    auth: 'sessionOrApiKey',
    body: api.createWorkspaceBodySchema,
    response: api.createWorkspaceResponseSchema,
    successStatus: 201,
    errorStatuses: [409],
  },
  {
    path: '/workspaces/slug-availability',
    method: 'get',
    operationId: 'getWorkspaceSlugAvailability',
    summary: 'Check workspace slug availability',
    tags: ['Workspaces'],
    auth: 'sessionOrApiKey',
    query: api.getWorkspaceSlugAvailabilityQuerySchema,
    response: api.getWorkspaceSlugAvailabilityResponseSchema,
  },
  {
    path: '/workspaces/{id}',
    method: 'patch',
    operationId: 'updateWorkspace',
    summary: 'Update a workspace',
    tags: ['Workspaces'],
    auth: 'sessionOrApiKey',
    params: api.updateWorkspaceParametersSchema,
    body: api.updateWorkspaceBodySchema,
    response: api.updateWorkspaceResponseSchema,
    successStatus: 200,
    errorStatuses: [403, 409],
  },
  {
    path: '/workspaces/{id}',
    method: 'delete',
    operationId: 'deleteWorkspace',
    summary: 'Delete a workspace',
    tags: ['Workspaces'],
    auth: 'sessionOrApiKey',
    params: api.deleteWorkspaceParametersSchema,
    successStatus: 204,
    errorStatuses: [403],
  },
  {
    path: '/workspaces/{id}/restore',
    method: 'post',
    operationId: 'restoreWorkspace',
    summary: 'Restore a soft-deleted workspace',
    tags: ['Workspaces'],
    auth: 'sessionOrApiKey',
    params: api.restoreWorkspaceParametersSchema,
    response: api.restoreWorkspaceResponseSchema,
    successStatus: 200,
    errorStatuses: [410],
  },
  {
    path: '/workspaces/{id}/storage-usage',
    method: 'get',
    operationId: 'getWorkspaceStorageUsage',
    summary: "Get a workspace's uploaded-file storage usage",
    tags: ['Workspaces'],
    auth: 'sessionOrApiKey',
    params: api.getWorkspaceStorageUsageParametersSchema,
    response: api.getWorkspaceStorageUsageResponseSchema,
    errorStatuses: [403, 404],
  },
  {
    path: '/files/{id}',
    method: 'get',
    operationId: 'getFile',
    summary: 'Get an uploaded file\u2019s metadata',
    tags: ['Files'],
    auth: 'sessionOrApiKey',
    params: api.getFileParametersSchema,
    response: api.getFileResponseSchema,
    errorStatuses: [403, 404],
  },
  {
    path: '/files/{id}',
    method: 'delete',
    operationId: 'deleteFile',
    summary: 'Delete an uploaded file',
    tags: ['Files'],
    auth: 'sessionOrApiKey',
    params: api.deleteFileParametersSchema,
    response: api.deleteFileResponseSchema,
    successStatus: 200,
    errorStatuses: [403, 404],
  },
  {
    path: '/data-sources',
    method: 'get',
    operationId: 'getDataSources',
    summary: 'List data sources',
    tags: ['Data Sources'],
    auth: 'sessionOrApiKey',
    query: api.getDataSourcesQuerySchema,
    response: api.getDataSourcesResponseSchema,
  },
  {
    path: '/data-sources',
    method: 'post',
    operationId: 'createDataSource',
    summary: 'Create a data source',
    tags: ['Data Sources'],
    auth: 'sessionOrApiKey',
    body: api.createDataSourceBodySchema,
    response: api.createDataSourceResponseSchema,
    successStatus: 201,
    errorStatuses: [404],
  },
  {
    path: '/data-sources/{id}',
    method: 'get',
    operationId: 'getDataSource',
    summary: 'Get a data source',
    tags: ['Data Sources'],
    auth: 'sessionOrApiKey',
    params: api.getDataSourceParametersSchema,
    response: api.getDataSourceResponseSchema,
  },
  {
    path: '/data-sources/{id}',
    method: 'patch',
    operationId: 'updateDataSource',
    summary: 'Update a data source',
    tags: ['Data Sources'],
    auth: 'sessionOrApiKey',
    params: api.updateDataSourceParametersSchema,
    body: api.updateDataSourceBodySchema,
    response: api.updateDataSourceResponseSchema,
    successStatus: 200,
  },
  {
    path: '/data-sources/{id}',
    method: 'delete',
    operationId: 'deleteDataSource',
    summary: 'Soft-delete a data source',
    tags: ['Data Sources'],
    auth: 'sessionOrApiKey',
    params: api.deleteDataSourceParametersSchema,
    successStatus: 204,
  },
  {
    path: '/data-sources/{id}/restore',
    method: 'post',
    operationId: 'restoreDataSource',
    summary: 'Restore a soft-deleted data source',
    tags: ['Data Sources'],
    auth: 'sessionOrApiKey',
    params: api.restoreDataSourceParametersSchema,
    response: api.restoreDataSourceResponseSchema,
    successStatus: 200,
    errorStatuses: [410],
  },
  {
    path: '/data-sources/{id}/columns',
    method: 'post',
    operationId: 'createDataSourceColumn',
    summary: 'Create a data source column',
    tags: ['Data Sources'],
    auth: 'sessionOrApiKey',
    params: api.createDataSourceColumnParametersSchema,
    body: api.createDataSourceColumnBodySchema,
    response: api.createDataSourceColumnResponseSchema,
    successStatus: 201,
  },
  {
    path: '/data-sources/{id}/columns/{columnId}',
    method: 'patch',
    operationId: 'updateDataSourceColumn',
    summary: 'Update a data source column',
    tags: ['Data Sources'],
    auth: 'sessionOrApiKey',
    params: api.updateDataSourceColumnParametersSchema,
    body: api.updateDataSourceColumnBodySchema,
    response: api.updateDataSourceColumnResponseSchema,
    successStatus: 200,
  },
  {
    path: '/data-sources/{id}/columns/{columnId}',
    method: 'delete',
    operationId: 'deleteDataSourceColumn',
    summary: 'Delete a data source column',
    tags: ['Data Sources'],
    auth: 'sessionOrApiKey',
    params: api.deleteDataSourceColumnParametersSchema,
    successStatus: 204,
  },
  {
    path: '/data-sources/{id}/columns/{columnId}/options',
    method: 'post',
    operationId: 'createSingleSelectOption',
    summary: 'Create a single-select option',
    tags: ['Data Sources'],
    auth: 'sessionOrApiKey',
    params: api.createSingleSelectOptionParametersSchema,
    body: api.createSingleSelectOptionBodySchema,
    response: api.createSingleSelectOptionResponseSchema,
    successStatus: 201,
    errorStatuses: [409],
  },
  {
    path: '/apps',
    method: 'get',
    operationId: 'getApps',
    summary: 'List apps',
    tags: ['Apps'],
    auth: 'session',
    query: api.listAppsQuerySchema,
    response: api.getAppsResponseSchema,
    errorStatuses: [404],
  },
  {
    path: '/apps',
    method: 'post',
    operationId: 'createApp',
    summary: 'Create an app',
    tags: ['Apps'],
    auth: 'session',
    body: api.createAppBodySchema,
    response: api.createAppResponseSchema,
    successStatus: 201,
    errorStatuses: [404],
  },
  {
    path: '/apps/{id}',
    method: 'get',
    operationId: 'getApp',
    summary: 'Get app details',
    tags: ['Apps'],
    auth: 'session',
    params: api.appParametersSchema,
    response: api.appDetailResponseSchema,
  },
  {
    path: '/apps/{id}',
    method: 'patch',
    operationId: 'updateApp',
    summary: 'Update an app',
    tags: ['Apps'],
    auth: 'session',
    params: api.appParametersSchema,
    body: api.updateAppBodySchema,
    response: api.updateAppResponseSchema,
    successStatus: 200,
  },
  {
    path: '/apps/{id}',
    method: 'delete',
    operationId: 'archiveApp',
    summary: 'Archive an app',
    tags: ['Apps'],
    auth: 'session',
    params: api.appParametersSchema,
    successStatus: 204,
  },
  {
    path: '/apps/{id}/keys',
    method: 'post',
    operationId: 'createApiKey',
    summary: 'Create an API key',
    tags: ['Apps'],
    auth: 'session',
    params: api.apiKeyParametersSchema,
    body: api.createApiKeyBodySchema,
    response: api.createApiKeyResponseSchema,
    successStatus: 201,
    errorStatuses: [409],
  },
  {
    path: '/apps/{id}/keys/{keyId}',
    method: 'delete',
    operationId: 'revokeApiKey',
    summary: 'Revoke an API key',
    tags: ['Apps'],
    auth: 'session',
    params: api.revokeApiKeyParametersSchema,
    successStatus: 204,
  },
  {
    path: '/apps/{id}/webhooks',
    method: 'get',
    operationId: 'getWebhooks',
    summary: 'List webhooks',
    tags: ['Apps', 'Webhooks'],
    auth: 'session',
    params: api.webhookParametersSchema,
    response: api.getWebhooksResponseSchema,
  },
  {
    path: '/apps/{id}/webhooks',
    method: 'post',
    operationId: 'createWebhook',
    summary: 'Create a webhook',
    tags: ['Apps', 'Webhooks'],
    auth: 'session',
    params: api.webhookParametersSchema,
    body: api.createWebhookBodySchema,
    response: api.createWebhookResponseSchema,
    successStatus: 201,
  },
  {
    path: '/apps/{id}/webhooks/{webhookId}',
    method: 'get',
    operationId: 'getWebhook',
    summary: 'Get a webhook',
    tags: ['Apps', 'Webhooks'],
    auth: 'session',
    params: api.webhookDetailParametersSchema,
    response: api.webhookResponseSchema,
  },
  {
    path: '/apps/{id}/webhooks/{webhookId}',
    method: 'patch',
    operationId: 'updateWebhook',
    summary: 'Update a webhook',
    tags: ['Apps', 'Webhooks'],
    auth: 'session',
    params: api.webhookDetailParametersSchema,
    body: api.updateWebhookBodySchema,
    response: api.updateWebhookResponseSchema,
    successStatus: 200,
  },
  {
    path: '/apps/{id}/webhooks/{webhookId}',
    method: 'delete',
    operationId: 'deleteWebhook',
    summary: 'Delete a webhook',
    tags: ['Apps', 'Webhooks'],
    auth: 'session',
    params: api.webhookDetailParametersSchema,
    successStatus: 204,
  },
  {
    path: '/apps/{id}/webhooks/{webhookId}/deliveries',
    method: 'get',
    operationId: 'getWebhookDeliveries',
    summary: 'List webhook deliveries',
    tags: ['Apps', 'Webhooks'],
    auth: 'session',
    params: api.webhookDeliveriesParametersSchema,
    response: api.getWebhookDeliveriesResponseSchema,
  },
  {
    path: '/apps/{id}/webhooks/{webhookId}/deliveries/{deliveryId}/resend',
    method: 'post',
    operationId: 'resendWebhookDelivery',
    summary: 'Resend a webhook delivery',
    tags: ['Apps', 'Webhooks'],
    auth: 'session',
    params: api.resendWebhookDeliveryParametersSchema,
    response: api.resendWebhookDeliveryResponseSchema,
    successStatus: 200,
    errorStatuses: [409],
  },
  {
    path: '/notifications',
    method: 'get',
    operationId: 'getNotifications',
    summary: 'List the current user notification inbox',
    tags: ['Notifications'],
    auth: 'session',
    query: api.getNotificationsQuerySchema,
    response: api.getNotificationsResponseSchema,
    responseMeta: { pagination: api.getNotificationsPaginationSchema },
    errorStatuses: [404],
  },
  {
    path: '/notifications/unread-counts',
    method: 'get',
    operationId: 'getNotificationUnreadCounts',
    summary: 'Get unread notification counts for the current user',
    tags: ['Notifications'],
    auth: 'session',
    response: api.getNotificationUnreadCountsResponseSchema,
  },
  {
    path: '/notifications/{id}',
    method: 'patch',
    operationId: 'patchNotification',
    summary: 'Mark a notification read or unread',
    tags: ['Notifications'],
    auth: 'session',
    params: api.patchNotificationParametersSchema,
    body: api.patchNotificationBodySchema,
    response: api.patchNotificationResponseSchema,
    successStatus: 200,
    errorStatuses: [404],
  },
  {
    path: '/notifications/read-all',
    method: 'post',
    operationId: 'postNotificationsReadAll',
    summary: 'Mark all notifications read for the current user',
    tags: ['Notifications'],
    auth: 'session',
    body: api.notificationsReadAllBodySchema,
    response: api.notificationsReadAllResponseSchema,
    successStatus: 200,
    errorStatuses: [404],
  },
  {
    path: '/notifications/subscriptions',
    method: 'get',
    operationId: 'getNotificationSubscriptions',
    summary: 'List the current user notification subscription rules',
    tags: ['Notifications'],
    auth: 'session',
    query: api.getNotificationSubscriptionsQuerySchema,
    response: api.getNotificationSubscriptionsResponseSchema,
    errorStatuses: [404],
  },
  {
    path: '/notifications/subscriptions/workspaces/{workspaceId}',
    method: 'put',
    operationId: 'putWorkspaceNotificationSubscription',
    summary: 'Set the workspace-level notification subscription',
    tags: ['Notifications'],
    auth: 'session',
    params: api.putWorkspaceNotificationSubscriptionParametersSchema,
    body: api.putWorkspaceNotificationSubscriptionBodySchema,
    response: api.putWorkspaceNotificationSubscriptionResponseSchema,
    successStatus: 200,
    errorStatuses: [404],
  },
  {
    path: '/notifications/subscriptions/pages/{pageId}',
    method: 'put',
    operationId: 'putPageNotificationSubscription',
    summary: 'Set a page-level notification subscription or exclusion',
    tags: ['Notifications'],
    auth: 'session',
    params: api.putPageNotificationSubscriptionParametersSchema,
    body: api.putPageNotificationSubscriptionBodySchema,
    response: api.putPageNotificationSubscriptionResponseSchema,
    successStatus: 200,
    errorStatuses: [404],
  },
  // THOTH-071 additions: browser Web Push config/registration, notification quiet-schedule
  // settings, temporary mute, and cross-workspace user timezone.
  {
    path: '/notifications/push-config',
    method: 'get',
    operationId: 'getNotificationPushConfig',
    summary: 'Get Web Push VAPID configuration',
    tags: ['Notifications'],
    auth: 'session',
    response: api.getPushConfigResponseSchema,
  },
  {
    path: '/notifications/push-subscriptions',
    method: 'post',
    operationId: 'registerPushSubscription',
    summary: 'Register a browser Web Push subscription',
    tags: ['Notifications'],
    auth: 'session',
    body: api.registerPushSubscriptionBodySchema,
    response: api.registerPushSubscriptionResponseSchema,
    successStatus: 200,
    errorStatuses: [400],
  },
  {
    path: '/notifications/push-subscriptions/{id}',
    method: 'delete',
    operationId: 'deletePushSubscription',
    summary: 'Disable a browser Web Push subscription',
    tags: ['Notifications'],
    auth: 'session',
    params: api.deletePushSubscriptionParametersSchema,
    response: api.deletePushSubscriptionResponseSchema,
    successStatus: 200,
    errorStatuses: [404],
  },
  {
    path: '/notifications/settings',
    method: 'get',
    operationId: 'getNotificationSettings',
    summary: 'Get notification quiet-schedule + mute settings',
    tags: ['Notifications'],
    auth: 'session',
    response: api.notificationSettingsResponseSchema,
  },
  {
    path: '/notifications/settings',
    method: 'patch',
    operationId: 'patchNotificationSettings',
    summary: 'Update the notification quiet-schedule',
    tags: ['Notifications'],
    auth: 'session',
    body: api.patchNotificationSettingsBodySchema,
    response: api.notificationSettingsResponseSchema,
    successStatus: 200,
    errorStatuses: [400],
  },
  {
    path: '/notifications/mute',
    method: 'post',
    operationId: 'muteNotifications',
    summary: 'Temporarily mute notifications until a future instant',
    tags: ['Notifications'],
    auth: 'session',
    body: api.postNotificationMuteBodySchema,
    response: api.notificationMuteResponseSchema,
    successStatus: 200,
    errorStatuses: [400],
  },
  {
    path: '/notifications/mute',
    method: 'delete',
    operationId: 'unmuteNotifications',
    summary: 'Clear the current temporary notification mute',
    tags: ['Notifications'],
    auth: 'session',
    response: api.notificationMuteResponseSchema,
    successStatus: 200,
  },
  {
    path: '/user/settings',
    method: 'get',
    operationId: 'getUserSettings',
    summary: 'Get cross-workspace per-user settings (timezone)',
    tags: ['User'],
    auth: 'session',
    response: api.getUserSettingsResponseSchema,
  },
  {
    path: '/user/settings',
    method: 'patch',
    operationId: 'patchUserSettings',
    summary: 'Update cross-workspace per-user settings (timezone)',
    tags: ['User'],
    auth: 'session',
    body: api.patchUserSettingsBodySchema,
    response: api.patchUserSettingsResponseSchema,
    successStatus: 200,
    errorStatuses: [400],
  },
  {
    path: '/platform/capabilities',
    method: 'get',
    operationId: 'getPlatformCapabilities',
    summary: 'Get platform capabilities for the current user',
    tags: ['Platform'],
    auth: 'session',
    response: api.getPlatformCapabilitiesResponseSchema,
  },
  {
    path: '/config',
    method: 'get',
    operationId: 'getAuthConfig',
    summary: 'Get authentication mode',
    tags: ['Config'],
    auth: 'none',
    response: api.getAuthConfigResponseSchema,
    responseWrapper: 'raw',
    successStatus: 200,
  },
] satisfies OperationRegistry;
