export type EmojiEntry = { char: string; keywords: string[]; category: string };

// A curated, dependency-free set of common unicode emojis grouped by category, used to power
// the page emoji picker's search grid. Native OS emoji rendering is used (no image sprites or
// external assets), so glyph appearance may vary slightly across platforms — that's acceptable.
export const EMOJI_LIST: EmojiEntry[] = [
  // Smileys
  { char: '😀', keywords: ['grinning', 'smile', 'happy'], category: 'Smileys' },
  { char: '😃', keywords: ['smiley', 'happy', 'joy'], category: 'Smileys' },
  { char: '😄', keywords: ['smile', 'happy', 'laugh'], category: 'Smileys' },
  { char: '😁', keywords: ['grin', 'happy'], category: 'Smileys' },
  { char: '😆', keywords: ['laughing', 'satisfied'], category: 'Smileys' },
  { char: '😅', keywords: ['sweat', 'smile', 'relief'], category: 'Smileys' },
  { char: '🤣', keywords: ['rofl', 'laughing'], category: 'Smileys' },
  { char: '😂', keywords: ['joy', 'tears', 'laugh'], category: 'Smileys' },
  { char: '🙂', keywords: ['slightly', 'smiling'], category: 'Smileys' },
  { char: '🙃', keywords: ['upside', 'down'], category: 'Smileys' },
  { char: '😉', keywords: ['wink'], category: 'Smileys' },
  { char: '😊', keywords: ['blush', 'happy'], category: 'Smileys' },
  { char: '😇', keywords: ['innocent', 'halo'], category: 'Smileys' },
  { char: '😍', keywords: ['heart', 'eyes', 'love'], category: 'Smileys' },
  { char: '🤩', keywords: ['star', 'struck', 'excited'], category: 'Smileys' },
  { char: '😘', keywords: ['kiss', 'love'], category: 'Smileys' },
  { char: '😋', keywords: ['yum', 'tongue', 'tasty'], category: 'Smileys' },
  { char: '😜', keywords: ['wink', 'tongue', 'silly'], category: 'Smileys' },
  { char: '🤪', keywords: ['zany', 'crazy'], category: 'Smileys' },
  { char: '😎', keywords: ['cool', 'sunglasses'], category: 'Smileys' },
  { char: '🥳', keywords: ['party', 'celebrate'], category: 'Smileys' },
  { char: '😏', keywords: ['smirk'], category: 'Smileys' },
  { char: '😒', keywords: ['unamused'], category: 'Smileys' },
  { char: '😞', keywords: ['disappointed'], category: 'Smileys' },
  { char: '😔', keywords: ['pensive', 'sad'], category: 'Smileys' },
  { char: '😢', keywords: ['cry', 'sad'], category: 'Smileys' },
  { char: '😭', keywords: ['sob', 'crying'], category: 'Smileys' },
  { char: '😡', keywords: ['angry', 'mad', 'rage'], category: 'Smileys' },
  { char: '😱', keywords: ['scream', 'shocked'], category: 'Smileys' },
  { char: '😴', keywords: ['sleep', 'tired'], category: 'Smileys' },
  { char: '🤔', keywords: ['thinking'], category: 'Smileys' },
  { char: '🤗', keywords: ['hug'], category: 'Smileys' },
  { char: '🤫', keywords: ['shush', 'quiet'], category: 'Smileys' },
  { char: '🥺', keywords: ['pleading', 'puppy'], category: 'Smileys' },
  { char: '😬', keywords: ['grimace', 'awkward'], category: 'Smileys' },
  { char: '🤯', keywords: ['mind', 'blown', 'exploding'], category: 'Smileys' },
  { char: '🤠', keywords: ['cowboy'], category: 'Smileys' },
  { char: '🥸', keywords: ['disguise', 'glasses'], category: 'Smileys' },
  { char: '🤓', keywords: ['nerd'], category: 'Smileys' },

  // People
  { char: '👋', keywords: ['wave', 'hello'], category: 'People' },
  { char: '👍', keywords: ['thumbs', 'up', 'like'], category: 'People' },
  { char: '👎', keywords: ['thumbs', 'down', 'dislike'], category: 'People' },
  { char: '👏', keywords: ['clap', 'applause'], category: 'People' },
  { char: '🙌', keywords: ['raised', 'hands', 'celebrate'], category: 'People' },
  { char: '🙏', keywords: ['pray', 'thanks', 'please'], category: 'People' },
  { char: '💪', keywords: ['muscle', 'strong'], category: 'People' },
  { char: '✍️', keywords: ['writing', 'hand'], category: 'People' },
  { char: '🤝', keywords: ['handshake', 'deal'], category: 'People' },
  { char: '🫶', keywords: ['heart', 'hands'], category: 'People' },
  { char: '🧑', keywords: ['person'], category: 'People' },
  { char: '👨', keywords: ['man'], category: 'People' },
  { char: '👩', keywords: ['woman'], category: 'People' },
  { char: '🧑‍💻', keywords: ['developer', 'coder', 'programmer'], category: 'People' },
  { char: '👨‍🎓', keywords: ['graduate', 'student'], category: 'People' },
  { char: '🧑‍🏫', keywords: ['teacher'], category: 'People' },
  { char: '🧑‍⚕️', keywords: ['doctor', 'health'], category: 'People' },
  { char: '🧙', keywords: ['wizard', 'mage'], category: 'People' },
  { char: '🦸', keywords: ['superhero', 'hero'], category: 'People' },
  { char: '👶', keywords: ['baby'], category: 'People' },
  { char: '👴', keywords: ['old', 'man', 'grandpa'], category: 'People' },
  { char: '👵', keywords: ['old', 'woman', 'grandma'], category: 'People' },
  { char: '💀', keywords: ['skull', 'death'], category: 'People' },
  { char: '👻', keywords: ['ghost'], category: 'People' },
  { char: '👽', keywords: ['alien'], category: 'People' },
  { char: '🤖', keywords: ['robot'], category: 'People' },

  // Animals
  { char: '🐶', keywords: ['dog', 'puppy'], category: 'Animals' },
  { char: '🐱', keywords: ['cat', 'kitten'], category: 'Animals' },
  { char: '🐭', keywords: ['mouse'], category: 'Animals' },
  { char: '🐹', keywords: ['hamster'], category: 'Animals' },
  { char: '🐰', keywords: ['rabbit', 'bunny'], category: 'Animals' },
  { char: '🦊', keywords: ['fox'], category: 'Animals' },
  { char: '🐻', keywords: ['bear'], category: 'Animals' },
  { char: '🐼', keywords: ['panda'], category: 'Animals' },
  { char: '🐨', keywords: ['koala'], category: 'Animals' },
  { char: '🐯', keywords: ['tiger'], category: 'Animals' },
  { char: '🦁', keywords: ['lion'], category: 'Animals' },
  { char: '🐮', keywords: ['cow'], category: 'Animals' },
  { char: '🐷', keywords: ['pig'], category: 'Animals' },
  { char: '🐸', keywords: ['frog'], category: 'Animals' },
  { char: '🐵', keywords: ['monkey'], category: 'Animals' },
  { char: '🐔', keywords: ['chicken'], category: 'Animals' },
  { char: '🐧', keywords: ['penguin'], category: 'Animals' },
  { char: '🐦', keywords: ['bird'], category: 'Animals' },
  { char: '🦆', keywords: ['duck'], category: 'Animals' },
  { char: '🦉', keywords: ['owl'], category: 'Animals' },
  { char: '🐺', keywords: ['wolf'], category: 'Animals' },
  { char: '🐗', keywords: ['boar'], category: 'Animals' },
  { char: '🐴', keywords: ['horse'], category: 'Animals' },
  { char: '🦄', keywords: ['unicorn'], category: 'Animals' },
  { char: '🐝', keywords: ['bee'], category: 'Animals' },
  { char: '🐛', keywords: ['bug', 'caterpillar'], category: 'Animals' },
  { char: '🦋', keywords: ['butterfly'], category: 'Animals' },
  { char: '🐌', keywords: ['snail'], category: 'Animals' },
  { char: '🐢', keywords: ['turtle'], category: 'Animals' },
  { char: '🐍', keywords: ['snake'], category: 'Animals' },
  { char: '🐙', keywords: ['octopus'], category: 'Animals' },
  { char: '🐳', keywords: ['whale'], category: 'Animals' },
  { char: '🐬', keywords: ['dolphin'], category: 'Animals' },
  { char: '🐟', keywords: ['fish'], category: 'Animals' },
  { char: '🦈', keywords: ['shark'], category: 'Animals' },
  { char: '🐊', keywords: ['crocodile'], category: 'Animals' },
  { char: '🦖', keywords: ['dinosaur', 'trex'], category: 'Animals' },

  // Food
  { char: '🍎', keywords: ['apple', 'fruit'], category: 'Food' },
  { char: '🍌', keywords: ['banana', 'fruit'], category: 'Food' },
  { char: '🍇', keywords: ['grapes', 'fruit'], category: 'Food' },
  { char: '🍉', keywords: ['watermelon', 'fruit'], category: 'Food' },
  { char: '🍓', keywords: ['strawberry', 'fruit'], category: 'Food' },
  { char: '🍒', keywords: ['cherries', 'fruit'], category: 'Food' },
  { char: '🍍', keywords: ['pineapple', 'fruit'], category: 'Food' },
  { char: '🥑', keywords: ['avocado'], category: 'Food' },
  { char: '🍅', keywords: ['tomato'], category: 'Food' },
  { char: '🥕', keywords: ['carrot'], category: 'Food' },
  { char: '🌽', keywords: ['corn'], category: 'Food' },
  { char: '🥐', keywords: ['croissant', 'bread'], category: 'Food' },
  { char: '🍞', keywords: ['bread'], category: 'Food' },
  { char: '🧀', keywords: ['cheese'], category: 'Food' },
  { char: '🍳', keywords: ['egg', 'cooking'], category: 'Food' },
  { char: '🥞', keywords: ['pancakes'], category: 'Food' },
  { char: '🍕', keywords: ['pizza'], category: 'Food' },
  { char: '🍔', keywords: ['burger', 'hamburger'], category: 'Food' },
  { char: '🍟', keywords: ['fries'], category: 'Food' },
  { char: '🌭', keywords: ['hotdog'], category: 'Food' },
  { char: '🌮', keywords: ['taco'], category: 'Food' },
  { char: '🍣', keywords: ['sushi'], category: 'Food' },
  { char: '🍜', keywords: ['noodles', 'ramen'], category: 'Food' },
  { char: '🍱', keywords: ['bento', 'lunchbox'], category: 'Food' },
  { char: '🍰', keywords: ['cake', 'dessert'], category: 'Food' },
  { char: '🎂', keywords: ['birthday', 'cake'], category: 'Food' },
  { char: '🍦', keywords: ['ice', 'cream'], category: 'Food' },
  { char: '🍩', keywords: ['donut'], category: 'Food' },
  { char: '🍪', keywords: ['cookie'], category: 'Food' },
  { char: '☕', keywords: ['coffee'], category: 'Food' },
  { char: '🍵', keywords: ['tea'], category: 'Food' },
  { char: '🍺', keywords: ['beer'], category: 'Food' },
  { char: '🍷', keywords: ['wine'], category: 'Food' },
  { char: '🥤', keywords: ['drink', 'soda'], category: 'Food' },

  // Activities
  { char: '⚽', keywords: ['soccer', 'football'], category: 'Activities' },
  { char: '🏀', keywords: ['basketball'], category: 'Activities' },
  { char: '🏈', keywords: ['football', 'american'], category: 'Activities' },
  { char: '⚾', keywords: ['baseball'], category: 'Activities' },
  { char: '🎾', keywords: ['tennis'], category: 'Activities' },
  { char: '🏐', keywords: ['volleyball'], category: 'Activities' },
  { char: '🏓', keywords: ['ping', 'pong', 'table', 'tennis'], category: 'Activities' },
  { char: '🏸', keywords: ['badminton'], category: 'Activities' },
  { char: '🥊', keywords: ['boxing'], category: 'Activities' },
  { char: '🎯', keywords: ['dart', 'target', 'goal'], category: 'Activities' },
  { char: '🎮', keywords: ['game', 'controller', 'gaming'], category: 'Activities' },
  { char: '🎲', keywords: ['dice', 'game'], category: 'Activities' },
  { char: '🎳', keywords: ['bowling'], category: 'Activities' },
  { char: '♟️', keywords: ['chess'], category: 'Activities' },
  { char: '🎨', keywords: ['art', 'palette', 'paint'], category: 'Activities' },
  { char: '🎭', keywords: ['theater', 'drama', 'masks'], category: 'Activities' },
  { char: '🎬', keywords: ['movie', 'clapper', 'film'], category: 'Activities' },
  { char: '🎤', keywords: ['microphone', 'sing'], category: 'Activities' },
  { char: '🎧', keywords: ['headphones', 'music'], category: 'Activities' },
  { char: '🎸', keywords: ['guitar', 'music'], category: 'Activities' },
  { char: '🎹', keywords: ['piano', 'music'], category: 'Activities' },
  { char: '🥁', keywords: ['drum', 'music'], category: 'Activities' },
  { char: '🏆', keywords: ['trophy', 'win'], category: 'Activities' },
  { char: '🥇', keywords: ['medal', 'gold', 'first'], category: 'Activities' },
  { char: '🎓', keywords: ['graduation', 'cap', 'education'], category: 'Activities' },
  { char: '🧩', keywords: ['puzzle'], category: 'Activities' },
  { char: '🎣', keywords: ['fishing'], category: 'Activities' },
  { char: '🏋️', keywords: ['weightlifting', 'gym'], category: 'Activities' },
  { char: '🧗', keywords: ['climbing'], category: 'Activities' },
  { char: '🏃', keywords: ['running'], category: 'Activities' },
  { char: '🧘', keywords: ['yoga', 'meditation'], category: 'Activities' },

  // Travel
  { char: '🚗', keywords: ['car'], category: 'Travel' },
  { char: '🚕', keywords: ['taxi'], category: 'Travel' },
  { char: '🚌', keywords: ['bus'], category: 'Travel' },
  { char: '🚓', keywords: ['police', 'car'], category: 'Travel' },
  { char: '🚑', keywords: ['ambulance'], category: 'Travel' },
  { char: '🚒', keywords: ['fire', 'truck'], category: 'Travel' },
  { char: '🚲', keywords: ['bike', 'bicycle'], category: 'Travel' },
  { char: '🏍️', keywords: ['motorcycle'], category: 'Travel' },
  { char: '✈️', keywords: ['airplane', 'flight', 'travel'], category: 'Travel' },
  { char: '🚀', keywords: ['rocket', 'launch', 'space'], category: 'Travel' },
  { char: '🛸', keywords: ['ufo'], category: 'Travel' },
  { char: '🚁', keywords: ['helicopter'], category: 'Travel' },
  { char: '⛵', keywords: ['sailboat', 'boat'], category: 'Travel' },
  { char: '🚢', keywords: ['ship'], category: 'Travel' },
  { char: '🚂', keywords: ['train', 'locomotive'], category: 'Travel' },
  { char: '🚇', keywords: ['metro', 'subway'], category: 'Travel' },
  { char: '🗺️', keywords: ['map', 'world'], category: 'Travel' },
  { char: '🧭', keywords: ['compass'], category: 'Travel' },
  { char: '🗽', keywords: ['statue', 'liberty'], category: 'Travel' },
  { char: '🗼', keywords: ['tower'], category: 'Travel' },
  { char: '🏰', keywords: ['castle'], category: 'Travel' },
  { char: '🏔️', keywords: ['mountain'], category: 'Travel' },
  { char: '🏖️', keywords: ['beach'], category: 'Travel' },
  { char: '🏝️', keywords: ['island'], category: 'Travel' },
  { char: '🌋', keywords: ['volcano'], category: 'Travel' },
  { char: '🏕️', keywords: ['camping', 'tent'], category: 'Travel' },
  { char: '🧳', keywords: ['luggage', 'suitcase'], category: 'Travel' },
  { char: '🗿', keywords: ['moai', 'statue'], category: 'Travel' },

  // Objects
  { char: '💡', keywords: ['idea', 'bulb', 'light', 'lightbulb'], category: 'Objects' },
  { char: '📌', keywords: ['pin', 'pushpin'], category: 'Objects' },
  { char: '📍', keywords: ['location', 'pin'], category: 'Objects' },
  { char: '📎', keywords: ['clip', 'paperclip'], category: 'Objects' },
  { char: '📝', keywords: ['note', 'memo', 'writing'], category: 'Objects' },
  { char: '📄', keywords: ['page', 'document'], category: 'Objects' },
  { char: '📃', keywords: ['page', 'curl'], category: 'Objects' },
  { char: '📋', keywords: ['clipboard'], category: 'Objects' },
  { char: '📁', keywords: ['folder'], category: 'Objects' },
  { char: '📂', keywords: ['folder', 'open'], category: 'Objects' },
  { char: '🗂️', keywords: ['index', 'dividers', 'organize'], category: 'Objects' },
  { char: '📅', keywords: ['calendar', 'date'], category: 'Objects' },
  { char: '📆', keywords: ['calendar', 'tear'], category: 'Objects' },
  { char: '📊', keywords: ['chart', 'bar', 'graph'], category: 'Objects' },
  { char: '📈', keywords: ['chart', 'trend', 'up', 'growth'], category: 'Objects' },
  { char: '📉', keywords: ['chart', 'trend', 'down'], category: 'Objects' },
  { char: '📚', keywords: ['books', 'library'], category: 'Objects' },
  { char: '📖', keywords: ['book', 'open'], category: 'Objects' },
  { char: '🔖', keywords: ['bookmark'], category: 'Objects' },
  { char: '🔍', keywords: ['search', 'magnifying', 'glass'], category: 'Objects' },
  { char: '🔒', keywords: ['lock', 'secure'], category: 'Objects' },
  { char: '🔑', keywords: ['key'], category: 'Objects' },
  { char: '🔨', keywords: ['hammer', 'tool'], category: 'Objects' },
  { char: '🛠️', keywords: ['tools', 'wrench'], category: 'Objects' },
  { char: '⚙️', keywords: ['gear', 'settings'], category: 'Objects' },
  { char: '💻', keywords: ['laptop', 'computer'], category: 'Objects' },
  { char: '🖥️', keywords: ['desktop', 'computer', 'monitor'], category: 'Objects' },
  { char: '⌨️', keywords: ['keyboard'], category: 'Objects' },
  { char: '🖱️', keywords: ['mouse'], category: 'Objects' },
  { char: '📱', keywords: ['phone', 'mobile'], category: 'Objects' },
  { char: '☎️', keywords: ['telephone', 'phone'], category: 'Objects' },
  { char: '💰', keywords: ['money', 'bag'], category: 'Objects' },
  { char: '💳', keywords: ['card', 'credit', 'payment'], category: 'Objects' },
  { char: '💵', keywords: ['money', 'dollar', 'cash'], category: 'Objects' },
  { char: '🎁', keywords: ['gift', 'present'], category: 'Objects' },
  { char: '📦', keywords: ['package', 'box'], category: 'Objects' },
  { char: '🔧', keywords: ['wrench', 'tool'], category: 'Objects' },
  { char: '🧰', keywords: ['toolbox'], category: 'Objects' },
  { char: '🕯️', keywords: ['candle'], category: 'Objects' },
  { char: '🔦', keywords: ['flashlight', 'torch'], category: 'Objects' },

  // Symbols
  { char: '❤️', keywords: ['heart', 'love', 'red'], category: 'Symbols' },
  { char: '🧡', keywords: ['heart', 'orange'], category: 'Symbols' },
  { char: '💛', keywords: ['heart', 'yellow'], category: 'Symbols' },
  { char: '💚', keywords: ['heart', 'green'], category: 'Symbols' },
  { char: '💙', keywords: ['heart', 'blue'], category: 'Symbols' },
  { char: '💜', keywords: ['heart', 'purple'], category: 'Symbols' },
  { char: '🖤', keywords: ['heart', 'black'], category: 'Symbols' },
  { char: '⭐', keywords: ['star'], category: 'Symbols' },
  { char: '🌟', keywords: ['star', 'glowing', 'sparkle'], category: 'Symbols' },
  { char: '✨', keywords: ['sparkles'], category: 'Symbols' },
  { char: '🔥', keywords: ['fire', 'hot'], category: 'Symbols' },
  { char: '💧', keywords: ['droplet', 'water'], category: 'Symbols' },
  { char: '🌈', keywords: ['rainbow'], category: 'Symbols' },
  { char: '☀️', keywords: ['sun', 'sunny'], category: 'Symbols' },
  { char: '⛅', keywords: ['cloud', 'sun', 'partly'], category: 'Symbols' },
  { char: '☁️', keywords: ['cloud'], category: 'Symbols' },
  { char: '⚡', keywords: ['lightning', 'bolt', 'electric'], category: 'Symbols' },
  { char: '❄️', keywords: ['snowflake', 'snow'], category: 'Symbols' },
  { char: '✅', keywords: ['check', 'done', 'complete'], category: 'Symbols' },
  { char: '❌', keywords: ['cross', 'no', 'wrong'], category: 'Symbols' },
  { char: '❓', keywords: ['question', 'mark'], category: 'Symbols' },
  { char: '❗', keywords: ['exclamation', 'mark', 'warning'], category: 'Symbols' },
  { char: '⚠️', keywords: ['warning', 'alert'], category: 'Symbols' },
  { char: '🚫', keywords: ['no', 'entry', 'forbidden'], category: 'Symbols' },
  { char: '💯', keywords: ['hundred', 'perfect'], category: 'Symbols' },
  { char: '🔴', keywords: ['red', 'circle'], category: 'Symbols' },
  { char: '🟠', keywords: ['orange', 'circle'], category: 'Symbols' },
  { char: '🟡', keywords: ['yellow', 'circle'], category: 'Symbols' },
  { char: '🟢', keywords: ['green', 'circle'], category: 'Symbols' },
  { char: '🔵', keywords: ['blue', 'circle'], category: 'Symbols' },
  { char: '🟣', keywords: ['purple', 'circle'], category: 'Symbols' },
  { char: '⬛', keywords: ['black', 'square'], category: 'Symbols' },
  { char: '⬜', keywords: ['white', 'square'], category: 'Symbols' },
  { char: '🔺', keywords: ['triangle', 'red'], category: 'Symbols' },
  { char: '💎', keywords: ['gem', 'diamond'], category: 'Symbols' },
  { char: '🔔', keywords: ['bell', 'notification'], category: 'Symbols' },
  { char: '🎉', keywords: ['party', 'celebrate', 'tada'], category: 'Symbols' },
  { char: '🎊', keywords: ['confetti', 'party'], category: 'Symbols' },
];

/**
 * Case-insensitive substring search over each emoji's `keywords` and `char`. Returns the full
 * (categorised) list unchanged when `query` is empty/whitespace, preserving category grouping.
 */
export function filterEmojis(query: string): EmojiEntry[] {
  const trimmed = query.trim().toLowerCase();
  if (!trimmed) {
    return EMOJI_LIST;
  }

  return EMOJI_LIST.filter(
    (entry) => entry.char.includes(trimmed) || entry.keywords.some((keyword) => keyword.includes(trimmed))
  );
}
